const IMG_PATH = '../assets/images/';
const ILLUS_PATH = '../assets/illus/';
const ICON_PATH = '../assets/icons/';
const images = {
  logo: require(`${IMG_PATH}logo.png`),
  logos: require(`${IMG_PATH}logos.png`),
  logoss: require(`${IMG_PATH}logoss.png`),
  userAvatar: require(`${IMG_PATH}userAvatar.png`),
  avatar1: require(`${IMG_PATH}avatar1.png`),
  avatar2: require(`${IMG_PATH}avatar2.png`),
  avatar3: require(`${IMG_PATH}avatar3.png`),
  cover1: require(`${IMG_PATH}cover1.png`),
  cover2: require(`${IMG_PATH}cover2.png`),
  cover3: require(`${IMG_PATH}cover3.png`),
  Photo: require(`${IMG_PATH}Photo.png`),
  Avatar: require(`${IMG_PATH}Avatar.png`),
  overlay: require(`${ILLUS_PATH}overlay.png`),
  bgWel: require(`${ILLUS_PATH}bgWel.png`),
  pr: require(`${ILLUS_PATH}pr.png`),
  cameraIcon: require(`${ICON_PATH}cameraIcon.png`),
  male: require(`${ICON_PATH}male.png`),
  female: require(`${ICON_PATH}female.png`),
  download: require(`${ICON_PATH}Download.png`),
  search: require(`${ICON_PATH}Search.png`),
  notifIndicator: require(`${ICON_PATH}notifIndicator.png`),
  notification: require(`${ICON_PATH}notification.png`),
  emoj: require(`${ICON_PATH}emoj.png`),
  send: require(`${ICON_PATH}send.png`),
  close: require(`${ICON_PATH}close.png`),
  comment: require(`${ICON_PATH}comment.png`),
  comment1: require(`${ICON_PATH}comment1.png`),
  setting: require(`${ICON_PATH}setting.png`),
  location: require(`${ICON_PATH}location.png`),
  edit: require(`${ICON_PATH}edit.png`),
};
export default images;
